ALTER TABLE `op_rbmx`
ADD COLUMN `RBID` bigint  NOT NULL COMMENT '日报id' AFTER `CZGH`;
ALTER TABLE `op_rbmx`
ADD COLUMN `SFMC` varchar(20)  NOT NULL COMMENT '收费名称' AFTER `SFXM`;
ALTER TABLE `op_rbmx`
ADD COLUMN `ZJJE` decimal(12,2)  NOT NULL COMMENT '收入合计' AFTER `SFJE`;
ALTER TABLE `op_rbmx`
ADD COLUMN `ZKJE` decimal(12,2)  NOT NULL COMMENT '折扣' AFTER `ZJJE`;
ALTER TABLE `op_rbmx`
ADD COLUMN `SJJE` decimal(12,2)  NOT NULL COMMENT '实际收入' AFTER `ZKJE`;

ALTER TABLE `op_rbmx`
ADD COLUMN `JZKSRQ` datetime   COMMENT '结账开始日期' AFTER `JZRQ`;
	ALTER TABLE `op_rbmx`
ADD COLUMN `HZRQ`  datetime COMMENT '汇总日期' AFTER `JZKSRQ`;
