ALTER TABLE `api_pacs_report`
ADD COLUMN `RHYTHM` varchar(200) NULL COMMENT '心率' AFTER `ZYH`,
ADD COLUMN `PRINTERVAL` varchar(200) NULL COMMENT 'P-R间期' AFTER `RHYTHM`,
ADD COLUMN `QRSDURATION` varchar(200) NULL COMMENT 'QRS时隙' AFTER `PRINTERVAL`,
ADD COLUMN `QRSAXIS` varchar(200) NULL COMMENT 'QRS电轴' AFTER `QRSDURATION`,
ADD COLUMN `QTINTERVAL` varchar(200) NULL COMMENT 'QT间期' AFTER `QRSAXIS`;


