ALTER TABLE `op_yjcf01`
MODIFY COLUMN `YJXH` int NOT NULL COMMENT '医技序号（主键）' FIRST,
MODIFY COLUMN `FPHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '发票号码(收费后回写)' AFTER `TJHM`,
MODIFY COLUMN `MZXH` int NULL DEFAULT NULL COMMENT '门诊序号(收费后回写)' AFTER `FPHM`,
MODIFY COLUMN `DJLY` int NULL DEFAULT NULL COMMENT '单据来源 | 1医生开单 2药房划价 3药房退药 4医技划价 5体检开单 6收费划价 7门诊退费' AFTER `ZFSJ`,
MODIFY COLUMN `FWBLSH` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '爱心卡套餐组套编号（暂未使用）' AFTER `DJLY`,
MODIFY COLUMN `SSSQID` int NULL DEFAULT NULL COMMENT '手术申请ID（手术申请使用）' AFTER `FWBLSH`,
MODIFY COLUMN `ZLSQDID` int NULL DEFAULT NULL COMMENT '治疗申请单ID(康复治疗使用)' AFTER `SSSQID`,
MODIFY COLUMN `CFSB` int NULL DEFAULT NULL COMMENT '处方识别（处方表的ID）' AFTER `XMLX`;
