CREATE TABLE `op_rbmx_sfmx`  (
  `RBID` bigint  NOT NULL COMMENT '日报ID'  PRIMARY KEY ,
  `CZGH` varchar(10) NOT NULL COMMENT '操作工号',
  `JZRQ` datetime NOT NULL COMMENT '结账日期',
	`XJ` decimal(12,2) NOT NULL COMMENT '现金',
  `ZP` decimal(12,2) NOT NULL COMMENT '支票',
	`POS` decimal(12,2) NOT NULL COMMENT 'POS',
	`HBWC` decimal(12,2) NOT NULL COMMENT '货币误差',
	`KYCK` decimal(12,2) NOT NULL COMMENT '扣预存款',	
	`YHJE` decimal(12,2) NOT NULL COMMENT '优惠金额',
	`JZJE` decimal(12,2) NOT NULL COMMENT '记账金额',
	`QTYS` decimal(12,2) NOT NULL COMMENT '医保记账',
	`SBJZ` decimal(12,2) NOT NULL COMMENT '商保记账',
	`QTJZ` decimal(12,2) NOT NULL COMMENT '其他记账',
	`ZJE` decimal(12,2) NOT NULL COMMENT '结算总收入',
	`YJJ_XJ` decimal(12,2) NOT NULL COMMENT '收预交款-现金',
	`YJJ_ZP` decimal(12,2) NOT NULL COMMENT '收预交款-支票',
	`YJJ_POS` decimal(12,2) NOT NULL COMMENT '收预缴款-POS',	
	`YJJ_HJ` decimal(12,2) NOT NULL COMMENT '收预缴款-合计',
	`TJJ_XJ` decimal(12,2) NOT NULL COMMENT '退预缴款-现金',
	`TJJ_ZP` decimal(12,2) NOT NULL COMMENT '退预缴款-支票',
	`TJJ_POS` decimal(12,2) NOT NULL COMMENT '退预缴款-POS',
	`TJJ_HJ` decimal(12,2) NOT NULL COMMENT '退预缴款-合计',
	`SS_HJ` decimal(12,2) NOT NULL COMMENT '现金支票pos合计',
  `SJH` varchar(100) NOT NULL COMMENT '收据号',
	`SJZS` varchar(10) NOT NULL COMMENT '收据张数',
	`SJJE` varchar(10) NOT NULL COMMENT '收据金额',
	`FPH` varchar(100) NOT NULL COMMENT '发票号',
	`FPZS` varchar(10) NOT NULL COMMENT '发票张数',
	`FPJE` varchar(10) NOT NULL COMMENT '发票金额',		
  `JGID` int NOT NULL COMMENT '机构id',
  `MZLB` varchar(10) NOT NULL COMMENT '门诊类别'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '门诊日报明细-收费明细' ;