ALTER TABLE `op_cf01`
ADD COLUMN `SHSJ` datetime(0) NULL COMMENT '审核时间' AFTER `SHZT`,
ADD COLUMN `SHYS` varchar(20) NULL COMMENT '审核医生代码' AFTER `SHSJ`,
ADD COLUMN `SHYSXM` varchar(20) NULL COMMENT '审核医生姓名' AFTER `SHYS`;