ALTER TABLE `api_pacs_report`
ADD COLUMN `ZYH` int(10) NULL default 0 COMMENT '住院号' AFTER `JZLSH`;

ALTER TABLE `api_pacs_report`
MODIFY COLUMN `DIAGDESC` text NULL DEFAULT NULL COMMENT '影像所见' AFTER `EXAMMETHOD`;

ALTER TABLE `api_pacs_report`
MODIFY COLUMN `IMG_URL` text NULL DEFAULT NULL COMMENT '影像URL地址' AFTER `MEDICAL_TECHNOLOGY_TYPE`;
